stages:
  - preparation
  - build
  - check
  - release
  - package

variables:
  # Build config
  BUILD_TYPE: Release
  BUILD_TESTS: "true"
  BUILD_CTEST: "true"
  CTEST_INCLUDE_REGEX: "" # Regex is given via ctest -R [regex]
  CTEST_EXCLUDE_REGEX: "" # Regex is given via ctest -E [regex]
  CPU_TARGET: ivybridge # envinf1 has oldest cpu
  ARTIFACTS_PAGES_URL: https://$CI_PROJECT_ROOT_NAMESPACE.$CI_PAGES_DOMAIN/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts

workflow:
  rules:
    # Disable CI for non-MR user-scoped pipelines
    - if: '$CI_MERGE_REQUEST_IID == null && $CI_PROJECT_PATH != "ogs/ogs"'
      when: never
    - if: "$CI_MERGE_REQUEST_LABELS =~ /.*(workflow::paused|ci skip).*/"
      when: never
    - if: $CI_MERGE_REQUEST_LABELS =~ /.*ci::web only.*/
      variables:
        WEB_ONLY: "true"
        CTEST_INCLUDE_REGEX: "nb-"
    - if: $CI_MERGE_REQUEST_IID # merge requests
    - if: $CI_COMMIT_TAG # tags, ogs/ogs repo only
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PROJECT_PATH == "ogs/ogs"' # master, ogs/ogs repo only
    - if: '$CI_COMMIT_BRANCH =~ /^v[0-9]\.[0-9]\.[0-9]/ && $CI_PROJECT_PATH == "ogs/ogs"' # release branches, e.g. v6.x.x

include:
  - local: "scripts/ci/extends/*.yml"
  - local: "/scripts/ci/pipelines/web.yml"
    rules:
      - if: $CI_MERGE_REQUEST_LABELS =~ /.*ci::web only.*/
  - local: "/scripts/ci/pipelines/regular.yml"
    rules:
      - if: $CI_PIPELINE_SOURCE != "schedule" && $CI_MERGE_REQUEST_LABELS !~ /.*ci::web only.*/
  - local: "/scripts/ci/pipelines/scheduled.yml"
    rules:
      - if: '$CI_PIPELINE_SOURCE == "schedule"'
