stages:
  - test
  - package

include:
  - local: '/scripts/ci/extends/container-maker-setup.yml'
  - local: '/scripts/ci/jobs/build_image.yml'
  - local: '/scripts/ci/jobs/build.yml'
  - local: '/scripts/ci/jobs/container.yml'
