stages:
  - test
  - checks
  - package

variables:
  CONTAINER_GCC_IMAGE: $CI_REGISTRY_IMAGE:gcc-$CI_COMMIT_REF_SLUG

include:
  - local: '/scripts/ci/extends/container-maker-setup.yml'
  - local: '/scripts/ci/jobs/build_image.yml'
  - local: '/scripts/ci/jobs/build.yml'
  - local: '/scripts/ci/jobs/checks.yml'
  - local: '/scripts/ci/jobs/container.yml'
