stages:
  - preparation
  - build
  - check
  - release
  - package

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        PYPI_PASSWORD: "${PYPI_TOKEN}"
        PYPI_REPO: pypi
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        PYPI_PASSWORD: "${TEST_PYPI_TOKEN}"
        PYPI_REPO: testpypi
    - if: $CI_MERGE_REQUEST_ID
      variables:
        CIBW_BUILD: cp39* cp310*

include:
  - local: "scripts/ci/extends/*.yml"
  - local: "/scripts/ci/jobs/meta.yml"

.wheels_template: &wheels_template
  stage: build
  needs: [meta]
  script:
    - pipx run cibuildwheel
  artifacts:
    paths:
      - wheelhouse/

build wheels linux:
  tags: [envinf3-shell]
  <<: *wheels_template

build wheels mac:
  tags:
    - mac
    - ${ARCHITECTURE}
  variables:
    CMAKE_OSX_DEPLOYMENT_TARGET: "10.15"
  parallel:
    matrix:
      - ARCHITECTURE: ["amd64", "arm64"]
  <<: *wheels_template

build wheels win:
  tags: [windows]
  extends:
    - .vs2019-environment
  <<: *wheels_template

publish wheels:
  stage: release
  needs: ["build wheels linux", "build wheels mac", "build wheels win"]
  tags: [envinf, shell]
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - when: never
  script:
    - >
      pipx run twine upload
      --repository ${PYPI_REPO}
      --username __token__
      --password ${PYPI_PASSWORD}
      wheelhouse/*
