build docs:
  stage: test
  image:
    name: $CONTAINER_GCC_IMAGE

  before_script:
    - mkdir -p build
    - cd build

  script:
    - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DOGS_USE_CONAN=OFF -DOGS_BUILD_PROCESSES=GroundwaterFlow
    - cmake --build . --target doc > >(tee make-docs.output)

  artifacts:
    expose_as: 'Doxygen'
    paths: ['build/docs/']

build:
  stage: test
  variables:
    BUILD_DIR: "build"
    CCACHE_DIR: "$CI_PROJECT_DIR/.ccache"
  image:
    name: $CONTAINER_GCC_IMAGE
  cache:
    paths:
      - .ccache
  extends: .test-artifacts

  before_script:
    - mkdir -p $BUILD_DIR
    - cd $BUILD_DIR

  script:
    - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DOGS_USE_CONAN=OFF -DOGS_BUILD_PROCESSES=GroundwaterFlow
    - cmake --build . > >(tee make.output)
    - cmake --build . --target tests
    - cmake --build . --target ctest
    - cp Testing/**/Test.xml Tests/ctest.xml
