build:
  stage: test
  variables:
    CCACHE_DIR: "$CI_PROJECT_DIR/.ccache"
  image:
    name: $CONTAINER_GCC_IMAGE
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  cache:
    paths:
      - .ccache

  before_script:
    - mkdir -p build
    - cd build

  script:
    - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DOGS_USE_CONAN=OFF -DOGS_BUILD_PROCESSES=GroundwaterFlow
    - cmake --build . > >(tee make.output)
    - cmake --build . --target tests
    - cmake --build . --target ctest -j 8

  artifacts:
    paths:
      - build/Testing/**/*.xml
      - build/Tests/testrunner.xml
      - build/make.output
    expire_in: 1 week
    reports:
      junit:
        - build/Tests/testrunner.xml
        - build/Testing/**/*.xml
